### ISSUE TITLE
Configure save location for Get/Set-gShellSettings

### ISSUE THREAD

**Issue by Fetch04** [squid808/gShell#11]
It would be nice to be able to set where the .bin or .json and .config files are saved.  I think using -Path would be intuitive for most folks on both Get-gShellSettings and Set-gShellSettings so that the files can be saved to and recalled from an arbitrary place.  This would be handy to have on servers especially, as the default save is tied to the account that is logged in.  C:\Users\username\AppData\Local\gShell is the current default if anyone is interested.

**Comment by squid808** [comment]
I've updated the code so that you can use Set-GShellSettings -AuthInfoPath "somepath" in release 0.0.9.0 - just got done testing it. You may have to relaunch powershell if for some reason it doesn't refresh in memory. Please test it out when the new release comes out!
