### ISSUE TITLE
Feature Request - Set-GAChromeosdevice cmdlet

### ISSUE THREAD

**Issue by sdteufelhunden** [squid808/gShell#12]
Currently the Set-GAChromeosdevice cmdlet only allows updating of the AnnotatedLocation, AnnotatedUser, OrgUnitPath, and Notes fields.  The AnnotatedAssetID field is the only writable field that is not currently available in the cmdlet.

Current scenario: I have a file with serial numbers and asset tags from our white glove service and in Powershell I am able to import the file, match serial numbers, and assign asset tag numbers to the Chromebooks I export with gShell, but I am not currently able to use the AnnotatedAssetID field.  I plan to work around this by updating one of the other fields and then using the chromebookinventory add-on to export, move the data to the correct field, and then import it back.  It would be nice if I could do it all in Powershell and minimize the chances for user error when moving the data in a spreadsheet.

**Comment by squid808** [comment]
This has been added to the 0.0.9.0 release whish is coming out soon. Once out, please give it a try and make sure it's working! Until then I'll close this request - thank you for your patience!
