### ISSUE TITLE
Support for Secure String

### ISSUE THREAD

**Issue by WestWolverine** [squid808/gShell#13]
Support for secure string so New-GAUser can be used within the same script of a new AD user account creation script. 

$password = Read-Host -AsSecureString "AccountPassword"
New-GAUser $username -GivenName $FirstName -FamilyName $LastName -domain $domain -Password $password

**Comment by squid808** [comment]
This should be available in release 0.0.9.0 for both New-GAUser and Set-GAUser. The parameter is SecureStringPassword. It seems like it works on my end, if you can test it out once I release the next installer I'd appreciate it! Closing until then.
