### ISSUE TITLE
Set-GAUser Boolean issues

### ISSUE THREAD

**Issue by swancrawford** [squid808/gShell#16]
Version 0.9.2 Set-GAUser boolean commands not recognized.

Set-GAUser user@domain.com -ChangePasswordAtNextLogin $true

Set-GAUser : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Set-GAUser user@domain.com -ChangePasswordAtNextLogin $true
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-GAUser], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,gShell.Cmdlets.Directory.GAUser.SetGAUserCommand

Reverted back to 0.8.1 working fine.

**Comment by thesmall** [comment]
I can't speak for how squid808 developed this cmdlet, but in PowerShell, you generally supply a boolean value to a parameter using a colon:

Set-GAUser User@domain.com -ChangePasswordAtNextLogin:$true

Does it work when using a colon?

**Comment by squid808** [comment]
Booleans should allow you to handle it either way, with or without the colon. 

Can you try installing 0.9.2 and trying it again? It sounds almost like you were using 0.9.1 (which had a very very similar error with Set-GAUser and the ambiguous parameter sets). I tested 0.9.2 and i also had no issue.

**Comment by swancrawford** [comment]
Yeah can confirm working on 0.9.2 sorry my bad just checked previous version I had installed was from gShell_0.0.9.0.msi so must have been 0.9.1

Thanks for the quick response love this tool. Another quick question while we are here :)

We share our Internal Wiki site with users via google sites and they receive a mail once added is this possible with gshell??

Cheers!

**Comment by squid808** [comment]
Unfortunately no, the Google Sites API is not part of gShell. It's not that I have anything against it, but the Google Sites API isn't part of the Admin SDK for various reason (mainly, it's an older api that requires significant under-the-hood work to get working).

Ultimately if there is enough want for it I may look in to considering that for a 1.1.x release as the main update, but it won't be part of the 1.0.x release. That said, if you or anyone else reading this is interested in working on that themselves let me know. It'd follow the same, very convoluted workflow I had to follow to get other APIs working, for example the Admin Settings API.

Sorry about that, I hate letting people down.
