### ISSUE TITLE
Using -TargetUserEmail without service account produces error. 

### ISSUE THREAD

**Issue by Allieway** [squid808/gShell#23]
Get-GGmailMessage : Nullable object must have a value.

I'm using it without -domain, on the default domain in gshell.

I just think it would be nice if it said Service account not enabled, and gave instructions on the Set-GShellServiceAccount Cmdlet(similarly to how it invokes scopes)

**Comment by squid808** [comment]
I'll look in to this to see what would be required and will report back.

**Comment by squid808** [comment]
...I just didn't say how long it would take. Sorry about the delay. At this time, if you try using a -TargetUserEmail without already having a service account saved, you'll see the following warning:
_WARNING: No service account was found for domain test.sjcny.edu. Please set a service account with Set-GShellServiceAccount, or see https://github.com/squid808/gShell/wiki/Service-Accounts for more information._

The warning will come prior to the error, which still shows up. As soon as you add a service account, the warning goes away. I'm ok with that. Slated for the next release. 👍 Will close once that's released.

**Comment by Allieway** [comment]
Sounds great, thanks!

**Comment by squid808** [comment]
You can find a [pre-release of version 0.10.0 on the downloads page](https://github.com/squid808/gShell/wiki/Downloads), with [information on the beta release on the news page](https://github.com/squid808/gShell/wiki/News). Please read up on the breaking changes mentioned, and test it out to see if you are having any issues.

Over the next month or so I'll work to fix any remaining issues and then switch it to a full release.

Thanks!
