### ISSUE TITLE
Restructure saved Auth files to better support secondary domains

### ISSUE THREAD

**Issue by squid808** [squid808/gShell#29]
Topic started [here](https://github.com/squid808/gShell/issues/27#issuecomment-253545668). Points of interest:
1) Restructure auth file to allow association of domains as parent and child domains
2) Make sure child domains grab information from the parent domain if they don't have it
3) Only allow parent domains to have service accounts, or only look at service accounts of parent domains.

**Comment by squid808** [comment]
@Allieway Regarding the OAuth Json file, I'm going to have to think about this a little bit more before taking action. Currently, my proposed solution is to populate the domains as normal, but have two extra properties of _ParentDomain_ and _ChildDomains_ and the values would be other domain names. Any users associated specifically with this domain would still fall under this domain, would still have their own API auth settings and one would still be a default. That way, if a service account is called for this domain or if no users are specified, it would be able to redirect to the primary domain referenced here. 

That's all well and good, but the problem is how to get and populate this information, and how to resolve issues. I would probably need to set up ```Set-GShellDomain``` to include something like ```-AddChildDomains``` and ```-ClearPrimaryDomain```, so you could do something like:
```Set-GShellDomain -Domain PrimaryDomain -AddChildDomains "SubDomain1",""SubDomain2"```
```Set-GShellDomain -Domain SubDomain1 -ClearPrimaryDomain```

Now, what happens if you authenticate first for SubDomain1, and then realize 'oh, should have done the primary domain first'. This would only matter if you already have a service account set up, and at that point... use the above options to properly set up the domains. I should probably make a ```Remove-GShellServiceAccount``` while I'm at it.

For my own record keeping and tracking:

1. Add ParentDomain and ChildDomains parameters to the domain object in each type of serialized file
2. Update functions to search up the tree to parent domains, if they exist, for default settings. setting functions will need to check for parent/child relationships for any domain, now, where applicable (eg, new user added to domain).
3. Update service account functions to only retrieve the service account from the parent domain
4. Update Set-GShellDomain to allow adding of child domains to a domain and clearing the parent domain. Complimentary ability to do the same from both ends?
5. Update Get-GShellDomain to allow listing of child/parent domains
6. Create Remove-GShellServiceAccount

**Comment by Allieway** [comment]
I like the whole general idea a bunch, and the direction you are taking to solve it with the organization of oauth also seems nice. But why not just make it simple to add primary/secondary? 
When you run `Get-GADomain -All` It lists all domains and shows which is primary when it's returned. It even shows domain aliases as well(which are different than regular sub domains, as every item that is part of a specific domain, also has the alias automatically attached).

Having a `Get-GShellDomains` or something similar that simply runs `Get-GADomain -All` and organizes the data in oauth is seemingly the easiest solution for this.  

> Now, what happens if you authenticate first for SubDomain1, and then realize 'oh, should have done the primary domain first'.

With what I proposed, oauth could just reorganize itself, if it detects a new primary is active, simply mark that domain as the new primary. Until someone runs that command to Get all domains, simply assume any domain added is a primary(as on the rarity someone adds multiple domains/users, it's even more rare to add multiple secondary domains/users). 

___

As I said previously, It would even be nice if gShell would run that automatically in the background if/when it detected a user has given authentication for that. Something like if the domain scopes are selected during invoke-scopemanager go ahead and get secondary domains and organize them in oauth. 

Everyone else looks good :)

**Comment by squid808** [comment]
Okey dokey, I'm working on this bit now - sorry for the delay! I've read it through and I think I understand what you are suggesting:

1) User authenticates for an API
2) gShell calls Get-GADomain -All and determines which domain is the primary
3) gShell writes/adjusts the OAuth file to compensate for the primary/secondary classifications

While what you propose _would_ appear to be easier, the issue is that you're requiring the user to [call an API endpoint](https://developers.google.com/admin-sdk/directory/v1/reference/domains/list) which would, in turn, require the user to authenticate for _that_ API. Best case scenario it requires the user to authenticate for an API they didn't want, worst case scenario it overwrites their Directory API saved auth information they already had or causes some kind of cyclical loop if the code is bad.

Beyond that, it would get confusing how to handle things. For example, when you authenticate the first time (let's say, by running a cmdlet like ```Get-GAUser```), it doesn't matter what domain you put in that cmdlet. When the browser opens, you are able to authenticate with ANY of your applicable accounts, and the information returned is based on that account chosen. So if someone runs the cmdlet to pull a user for the secondary domain, and they authenticate as an admin for a secondary domain, gShell is none the wiser and would just continue on. (Granted, this could be fixed by checking the user's list of domains, but then we're back to requiring that additional API authentication).

I think that at the point where a user is an admin in the position where they have multiple domains, it'd be reasonable that they should be able enough to run an additional cmdlet to set up the secondary domain as a [hopefully] one-time setup. As you noted, it'd be a rare enough occurrence.

I'm working on that now, based on the list I wrote previously; once I get it working I'll put it in the next preview release of gShell - hopefully you'll be able to test it out!

**Comment by squid808** [comment]
This should be set up. I yet need to write a bit of documentation for it, but it goes like this:

Via the Set-GShellDomain cmdlet:
- You can now add or remove a (just one) parent domain to any domain you have stored in your auth files.
- You can now add or remove zero or more child domains to any domain you have stored in your auth files.
- Doing any of the actions sets the other half of the pair up for you, so you don't need to do it twice.

When you have a parent/child relationship set up, any calls that would normally go to the child domain [will be resolved to the parent domain](https://github.com/squid808/gShell/commit/6f51c3bd15465123592152ece9618f4ddb437cec#diff-00e58666d44b642323f229a3b5b1891bL121), even when specified (in order to remove ambiguities of intent).

The rules of operation and procedures are as follows:
Authentication information is stored in the auth file, and retrieved via the combination of the auth domain and auth user (the user and domain used to authenticate the API). This information can be separate from what is being queried in a cmdlet. The order of processing is as follows:

1. Check for any explicitly provided GAuthId information
a.  If the GAuthId contains an @ symbol, it is expected that the parameter contains both a username and a domain to use in trying to retrieve it from the saved auth file
b. If the GAuthId does not contain an @ symbol, it first checks to see if it is a domain. If so, get that domain's default user, if any. If not, check the default domain and then other domains, if any, to see if that user belongs to that domain.
c. If no GAuthId is provided, or the information does not fully match anything stored (ie, just the domain matches, but not the username) do nothing
2. If auth domain and / or auth user are null, try to retrieve them from the defaults stored
3. If we have thus far established an auth domain but have no auth user, check to see if it has a parent domain. If so, check the parent's parent until you find a top-level parent. If a parent is found, use that domain's default auth user.
4. Parameters that are [by Google] required to provide a full email address can be provided as just an account (sans a domain). If a full address is not provided, the domain will be filled in by:
a. The provided GAuthId domain, if any
b. The default authenticated domain, if any

To illustrate this, assume you have domains domA and domB, with identical users in both with domA as the default domain. If you authorize both domains separately but in a valid manner via an admin account, you can assume the following examples would yield the following results:

`Get-GaUser user` => no GAuthId info provided, defaults and retrieves user@domaA.com
`Get-GaUser user@domB.com` => no GAuthId info provided, defaults to domA and fails since domA doesn't have permission to get info from domB
`Get-GaUser user -gauthId domA.com` => points to auth info for domA, retrieves user@domA.com
`Get-GaUser user -gauthId domB.com` => points to auth info for domB, retrieves user@domB.com
`Get-GaUser user@domB.com -gauthId domA.com` => GAuthId info provided for domA, fails since domA doesn't have permission to get info from domB

Now, let's assume we set domC as a _child_ to domA; domC has not been authenticated and has no default user:

`Get-GaUser user` => no GAuthId info provided, defaults and retrieves user@domaA.com
`Get-GaUser user@domC.com` => no GAuthId info provided, defaults to domA and since domA has permission to get info from domC, we get user@domC.com
`Get-GaUser user -gauthId domA.com` => points to auth info for domA, retrieves user@domA.com
`Get-GaUser user -gauthId domC.com` => points to auth info for domC, which (due to no default user) redirects to auth info for parent domain domA, which has access to domC. however, gShell remembers that you likely were looking for user@domC.com, and retrieves user@domC.com
`Get-GaUser user@domC.com -gauthId domA.com` => GAuthId info provided for domA, but looking for user at domC. It works since domA has permission to get info from domC.

If you then authenticated domC and gave it a default user, the only one that would change is this:
`Get-GaUser user -gauthId domC.com` => points to auth info for domC and retrieves user@domC.com

In this case, there is no redirecting to the parent information since you specified a domain that had a default auth user. It would be functionally the same as `Get-GaUser user -gauthId authUser@domC.com`

It can get hairy, since there are a lot of assumptions going on here, but the idea is this:
1. Use the GAuthId when you need to specify any auth user or auth domain different from the default.
2. If you are using a primary/parent domain setup, and you do have separate authentications set up for each domain, use the GAuthId parameter to discern with auth info you want to use.
3. If you want to get information for a child domain through a parent domain, either:
a. make sure the child domain doesn't have a default user and call `Get-GAUser user -GAuthId subdomain.com`
b. call things explicitly, like `Get-GAUser user@subdomain.com -GAuthId parentdomain.com` or some variation thereof

Now, if you're nearly as confused as I am right now, hang on and I'll be getting the new installer ready shortly. I may have to wait until tomorrow to do it, but it's coming along with a list of all the changes and additions.

**Comment by squid808** [comment]
You can find a [pre-release of version 0.10.0 on the downloads page](https://github.com/squid808/gShell/wiki/Downloads), with [information on the beta release on the news page](https://github.com/squid808/gShell/wiki/News). Please read up on the breaking changes mentioned, and test it out to see if you are having any issues.

Over the next month or so I'll work to fix any remaining issues and then switch it to a full release.

Thanks!
