### ISSUE TITLE
Deprecated Google API's 

### ISSUE THREAD

**Issue by whume** [squid808/gShell#3]
Google has been sending emails regarding the discontinuation of several of its API's on April 20th is gshell going to be affected by this?

Admin Audit
Google Apps Profiles
Provisioning
Reporting
Reporting Visualization

Thanks and great product!

**Comment by squid808** [comment]
I updated gShell to use the new APIs a while back, so there are no longer any dependencies on the gData libraries. There should be no issues!

**Comment by squid808** [comment]
Bad commit message with improper issue ID #, please ignore.
