### ISSUE TITLE
Get-GACalendar parameter position is strange.

### ISSUE THREAD

**Issue by Allieway** [squid808/gShell#32]
[wiki](https://github.com/squid808/gShell/wiki/Get-GACalendar#one-default) shows `-Customer` as position 0. 

`Get-GACalendar -CalendarResourceId "calendarstring"` is working(Which means gShell is appropriately supplying google API with my_customer even when not supplied by the user.)
`Get-GACalendar "calendarstring"` prompts the request for a calendar resource id(in my oppinion Should match [other gShell Cmdlets](https://github.com/squid808/gShell/wiki/Get-GAUser#-customer) with gShell automatically filling in customer for you, and having the Id as first parameter. 

I do see that google API actually does require customer for calendars, and does not for the other resources in directory api. But I think it would be good to change this in gShell for the sake of making GACalendar the same as it's directory API friends, and also Get-GCalendar.

**Comment by squid808** [comment]
I'm really not sure what is going on here. I've updated the wiki page locally and it's not updating on the web. I manually changed those lines and pushed it again, and it's still not updating. I'm concerned what this means about the state of the rest of the wiki. I'm going to see if there is any way I can do a complete refresh.

**Comment by squid808** [comment]
I dunno, it's bollocks. I manually updated it on the web and it seems to be fixed. The cmdlet and docs will match upon next release, at which point this will be closed.

**Comment by squid808** [comment]
You can find a [pre-release of version 0.10.0 on the downloads page](https://github.com/squid808/gShell/wiki/Downloads), with [information on the beta release on the news page](https://github.com/squid808/gShell/wiki/News). Please read up on the breaking changes mentioned, and test it out to see if you are having any issues.

Over the next month or so I'll work to fix any remaining issues and then switch it to a full release.

Thanks!
