### ISSUE TITLE
Classroom Guardians

### ISSUE THREAD

**Issue by sauced1** [squid808/gShell#34]
New feature of Classroom is to add a guardian's email address for the teacher to send notifications. Can this be implemented in a future release of gShell?

**Comment by squid808** [comment]
This should be complete and present in the next release, see [this commit](https://github.com/squid808/gShell/commit/1e6b47f96d534e6cc206c48dfdafba073bf74fa2).

**Comment by squid808** [comment]
You can find a [pre-release of version 0.10.0 on the downloads page](https://github.com/squid808/gShell/wiki/Downloads), with [information on the beta release on the news page](https://github.com/squid808/gShell/wiki/News). Please read up on the breaking changes mentioned, and test it out to see if you are having any issues.

Over the next month or so I'll work to fix any remaining issues and then switch it to a full release.

Thanks!
