### ISSUE TITLE
Get-GAUser does not populate field values from custom schema

### ISSUE THREAD

**Issue by DaveBlackburn** [squid808/gShell#38]
(Get-GAUser UserNameHere -Projection Full).userObject does not populate with values in Custom Schema fields.

**Comment by squid808** [comment]
Ok, this should be resolved in the next release... which will hopefully come out soon. I'll close the ticket at that time. Thank you!

**Comment by squid808** [comment]
You can find a [pre-release of version 0.10.0 on the downloads page](https://github.com/squid808/gShell/wiki/Downloads), with [information on the beta release on the news page](https://github.com/squid808/gShell/wiki/News). Please read up on the breaking changes mentioned, and test it out to see if you are having any issues.

Over the next month or so I'll work to fix any remaining issues and then switch it to a full release.

Thanks!
