### ISSUE TITLE
Missing information for gDrive objects

### ISSUE THREAD

**Issue by prsgroup** [squid808/gShell#39]
Opened ticket per your request.

Cmdlets Get-GdriveFile and Get-DriveRevision are only returning very little information for the objects. The former returns only Id, Kind, MimeType and Name and Get-DriveRevision returns only Id, Kind, MimeTypem, ModifiedTimeRaw and ModifiedTime.

...
leExtension         : 
FolderColorRgb        : 
FullFileExtension     : 
HeadRevisionId        : 
IconLink              : 
Id                    : 0B-CBGi7cpmvGUTFOYm9yRzFzZAB
ImageMediaMetadata    : 
IsAppAuthorized       : 
Kind                  : drive#file
LastModifyingUser     : 
Md5Checksum           : 
MimeType              : image/png
ModifiedByMeTimeRaw   : 
ModifiedByMeTime      : 
ModifiedTimeRaw       : 
ModifiedTime          : 
Name                  : invite-2.png
OriginalFilename      : 
OwnedByMe             : 
Owners                : 
Parents               : 
Permissions           : 
Properties            : 
QuotaBytesUsed        : 
Shared                : 
SharedWithMeTimeRaw   : 
...

Regards,
Rick

**Comment by squid808** [comment]
So, I've thought a lot about how to handle this, and I think I have the best answer. Many (not all) of the Google APIs support something called Standard Parameters, or some variation on that concept. Primarily, there is one standard parameter across almost all of the APIs that gShell uses - Fields.

I could have just added -Fields to every cmdlet, but I got to thinking there could be more in the future we would need to add, and that could get messy. Plus, updating that many lines of code took me too long to want to do repeatedly in the future. So I've added a new Cmdlet to act as a wrapper for this and two other existing parameters:
```New-GShellStandardQueryParameters```

It's long, but you won't need it for most current cmdlets. However, for something like Google Drive, you'd use it like this:

    Get-GDriveFile -FileId $SomeDriveFileId -StandardQueryParams `
        (New-GShellStandardQueryParameters -Fields "*")

And that, is that. I've just finished adding it to all of the cmdlets that can use it in my development branch; when I make the next release I'll be doing like a beta or preview download first, so keep an eye on the ticket for an update when that comes out.

**Comment by squid808** [comment]
You can find a [pre-release of version 0.10.0 on the downloads page](https://github.com/squid808/gShell/wiki/Downloads), with [information on the beta release on the news page](https://github.com/squid808/gShell/wiki/News). Please read up on the breaking changes mentioned, and test it out to see if you are having any issues.

Over the next month or so I'll work to fix any remaining issues and then switch it to a full release.

Thanks!
