### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by ErikN85** [squid808/gShell#40]
I need a little bit help. I want to transfer all data of a user to another user like on the pic but i cant find the right command to do this.

I think it's "new-GDrivePermission". But i don't know how to config is command to make the same like the pic.

<img width="340" alt="transfer" src="https://cloud.githubusercontent.com/assets/24697814/21389789/b7b22e7a-c783-11e6-81b3-ee49399e1320.PNG">

**Comment by squid808** [comment]
GDrive would be something good for a single item, or selected items, but you would need to set up a service account. I haven't done it myself but if you want what you see in the picture, have you tried the [GDataTransfer cmdlets](https://github.com/squid808/gShell/wiki/Cmdlets-Index#datatransfer)?

**Comment by ErikN85** [comment]
Can you give me an example how I should write this. 

I try this one too 

New-GDataTransferDataObj -NewOwnerUserId max.mustermann -OldOwnerUserId max.mustermann2

but no effects

**Comment by squid808** [comment]
Sure thing. I hadn't done it yet so it took a bit of testing. I'm including two code bits, one for the current release and one for the upcoming release that fixes a small issue with collection parameters. This is a verbose way of doing it, you can of course shave it down considerably if you want. Though it seems complex, please keep in mind that this is how Google has it set up on their end - you could wrap it in a cmdlet or function if you plan on doing this often.

Current version:
```
$app = Get-GDataTransferApplication -All | where Name -eq "Drive and Docs"
$old = get-gauser oldUserNameHere
$new = get-gauser newUserNameHere
$ADO = New-GDataTransferApplicationDataObj -ApplicationId $app.Id
$DTO = New-GDataTransferDataObj -OldOwnerUserId $old.userObject.Id `
    -NewOwnerUserId $new.userObject.Id
$DTO.ApplicationDataTransfers = New-Object ("System.Collections.Generic.List[{0}]" -f $ADO.GetType())
$DTO.ApplicationDataTransfers.Add($ADO)
$Transfer = New-GDataTransfer -DataTransferBody $DTO
Get-GDataTransfer -DataTransferId $Transfer.Id
```

Next version (fixes the need to make a generic list object):
```
$app = Get-GDataTransferApplication -All | where Name -eq "Drive and Docs"
$old = get-gauser oldUserNameHere
$new = get-gauser newUserNameHere
$DTO = New-GDataTransferDataObj -OldOwnerUserId $old.userObject.Id ` 
    -NewOwnerUserId $new.userObject.Id -ApplicationDataTransfers `
    (New-GDataTransferApplicationDataObj -ApplicationId $app.Id)
$Transfer = New-GDataTransfer -DataTransferBody $DTO
Get-GDataTransfer -DataTransferId $Transfer.Id
```

The `New-GDataTransfer` is what initiates the transfer, and you use `Get-GDataTransfer` to check the status of it (in the `OverallTransferStatusCode` member of the result - you'll see something like _inProgress_ or _Completed_).
