### ISSUE TITLE
Get-GAUser : Value cannot be null

### ISSUE THREAD

**Issue by johnmccrae** [squid808/gShell#49]
Brand new installation, just set the key and clientID which work fine - I can run GAM from the command line using the same data and it correctly gets user data back.

I am attempting to run either/both: Get-GAUser <me> or Get-GAUser -Userkey <me> and I get this:

`Get-GAUser : Value cannot be null. Parameter name: task

At line:1 char:1
 Get-GAUser me
 ~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [Get-GAUser], ArgumentNullException
     FullyQualifiedErrorId : System.ArgumentNullException,gShell.Cmdlets.Directory.GAUser.GetGAUserCommand`

What am I doing wrong please? Running the 10.2 build

**Comment by johnmccrae** [comment]
Killing this. It was not clear but running Invoke-GShellScopeManager corrected the issue

**Comment by squid808** [comment]
Hey John,

Sorry for the delay. I'm not sure what happened here, I haven't been able to reproduce the issue just yet. If running the invoke-gshellscopemanager resovled it, then it sounds like something didn't fire when it should have (which would have prompted you to handle the scopes without having to call that Cmdlet.)

I'll keep my eyes open for this issue and will see if I can reproduce and fix it in the future. Thank you!
