### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by avelis26** [squid808/gShell#5]
The redirect URI in the request: http://localhost:59780/authorize/ did not match a registered redirect URI.

Looks like only authorized redirect URI is http://localhost ... Little help ?

**Comment by squid808** [comment]
That sounds like an issue with the OAuth settings. A few questions - are you using the default client ID, or did you set a new one with Set-gShellClientSecrets? Either way, what cmdlets are you running that lead up to this error?

**Comment by avelis26** [comment]
This is all during initial set up. I haven't been able to run any cmdlets because I can't seem to get past this issue.

I'm simply running Invoke-ScopeManager to get everything set up. At no point does it ask me for a client ID that I'm aware of. It does ask me which google account to use (since I'm usually logged into multiple) and I select the right one.

**Comment by squid808** [comment]
Thanks for the info. Unfortunately gShell does not anywhere specify the redirect uri - those are [provided by default](https://developers.google.com/identity/protocols/OAuth2InstalledApp#choosingredirecturi) when someone creates OAuth credentials using the [Developer's Console](https://console.developers.google.com). I've never run in to the issue you're seeing, but what is happening here is after you choose your account, there is a bunch of back-and-forth between your browser and google, and at some point the Client Id and Secret that gShell provides by default is sent to Google, and in return Google sends back the Redirect URIs. From the first link:
> When you create a client ID in the Google Developers Console, two redirect_uris are created for you: urn:ietf:wg:oauth:2.0:oob and http://localhost. The value your application uses determines how the authorization code is returned to your application.

In this case, the 'application' it is referring to is not gShell, but the [.Net APIs provided by Google](https://developers.google.com/admin-sdk/directory/v1/api-lib/dotnet?hl=en) that gShell is written on.

That said, normally all of that should be handled automagically using the first URI, but for some reason your PC seems to using the localhost option. I'd be lying if I said I understood why. I'll mark this as a bug for now, but I am wholly unable to reproduce it.

In the meantime, make sure you're using PowerShell v3+, and try a different computer to see if that helps. I'll let you know if I can find anything else, but I don't think that it's anything I have control over at this point.

**Comment by avelis26** [comment]
Sure thing... I'll see about repo'ing on another machine. BTW currently I'm testing on a Win7x64 using Chrome and PSv4

**Comment by squid808** [comment]
Still having issues? I put out a debug release you may want to try, just in case. See the info on the discussion board [here](https://groups.google.com/d/msg/gshell-discuss/PwDWYnYUnfY/xPqh4_u2IAAJ).

**Comment by avelis26** [comment]
Hey sorry it took so long. This whole migration app was built with
PowerShell and most of the scripts use GAM. So I'm using PowerShell to call
python ... go figure :P
I would love to take GAM out of the equation and use gShell but just
haven't had the time for testing. Will do soon.

**Comment by hitmany** [comment]
Hey guys, I has same issue. But now I found solution:
Enable Google Console in Google Apps Admin in Applications section
Login in to google console, create project, create credentials with Windows CLi option
And use Set-gShellClientSecrets -ClientId HEREID -ClientSecret HERESECRET
Then you can use Get-GAUser with your domain
Use  admin:directory_v1 scope, accept API access and its WORKING! YAY!

**Comment by hitmany** [comment]
And also thank you squid808 for your great work, my script in Powershell now can work with new Google API without any mindf*ck

**Comment by squid808** [comment]
Hi guys, thanks for the updates. I just updated all the docs for [0.0.8.0](https://github.com/squid808/gShell/wiki/News), so please give that a try and let me know if there are any further issues/. @hitmany Thanks for the update, I've updated some of the wording in [Getting Started](https://github.com/squid808/gShell/wiki/Getting-Started) and [Set-gShellClientSecrets](https://github.com/squid808/gShell/wiki/Set-gShellClientSecrets) to try and make that more clear, please check that out too.

**Comment by squid808** [comment]
Hi all. Please give the newest version a try. If that doesn't work, please reopen the issue and let me know. Otherwise, closing as stale.
