### ISSUE TITLE
get-gdrivepermission missing info? 

### ISSUE THREAD

**Issue by k0d3r3d** [squid808/gShell#53]
When running get-gdrivepermission, the result seems to be missing a lot of details, is ita . API scope issue? I have the scopes setup for Drive. 

![image](https://cloud.githubusercontent.com/assets/20447286/25112649/87d535a0-23c0-11e7-99ed-573008096207.png)
 if I run get-gdrivefile  I get minimal info as well. 

![image](https://cloud.githubusercontent.com/assets/20447286/25112695/dcc3f2fe-23c0-11e7-9d07-c51fb4eb0f94.png)

**Comment by squid808** [comment]
That is a 'feature' of the Google Drive API - by default they only include the information you see, perhaps to make things run quicker and take less bandwidth. To resolve this, please use `New-GShellStandardQueryParameters` as per issue #39, like so:
```
Get-GDriveFile -FileId $SomeDriveFileId -StandardQueryParams `
    (New-GShellStandardQueryParameters -Fields "*")
```

I'll close the ticket for now, let me know if that doesn't help.

Cheers,

Spencer

**Comment by k0d3r3d** [comment]
Sweet that worked thanks :) 

you had a typo  New-GShellStandardQueryParameters  didn't work but  New-GShellStandardQueryParameters**obj**  did.

**Comment by squid808** [comment]
Ah, thanks for catching that. That's an obscenely long Cmdlet name :)
