### ISSUE TITLE
Request for Installation Guide

### ISSUE THREAD

**Issue by avelis26** [squid808/gShell#6]
Any chance you could write up a quick blurb on how to go from your source files to an importable module for Powershell ?

**Comment by squid808** [comment]
I'm not sure I understand the question - are you looking for instructions on how to compile and execute the code? If so, there are some key files missing intentionally, as per [this issue](https://github.com/squid808/gShell/issues/1). If you mean more along the lines of something like 'what do I do with the files once compiled', head on over to the [Discussion Groups](https://github.com/squid808/gShell/wiki/Discussion-Groups) and we can talk about it there. If it's neither of those, let me know, but I feel the Discussion Groups may end up being a better place for it regardless if it's not a bug or issue.

**Comment by avelis26** [comment]
Good point... I'll send this over to discussion side.
And I figured out how to compile it to a DLL and import it as a module so no worries there. I honestly didn't know powershell could import DLL's... always thought modules had to be psm1 files. I learned something lol.
