### ISSUE TITLE
Get-GEmailSettingsDelegation "Value cannot be null"

### ISSUE THREAD

**Issue by dwestness** [squid808/gShell#64]
I have a script that runs periodically and it has been working for some time without issue. I have noticed that now it is failing to to query the email delegates using the following command:
Get-GEmailSettingsDelegation user@domain.com -domain domain.com

The output i receive is: "Get-GEmailSettingsDelegation : Value cannot be null."

I have verified via the scope manager that all proper API scopes are chosen (as indicated as a possible solution from another issue)

**Comment by coolsammy** [comment]
I am experiencing the same issue.
@dwestness have you been able to get resolution for this and if yes, do you mind sharing

**Comment by dwestness** [comment]
Unfortunately i never did get this sorted out. I ran into a few other issues with the module as well. Ended up just switching to using GAM
