### ISSUE TITLE
ClientId is in your code. 

### ISSUE THREAD

**Issue by LindaLawton** [squid808/gShell#8]
You should regenerate the secret on your project in Google developers console, and remove it from the code.     

[Googles terms of service](http://googledevelopers.blogspot.dk/2014/11/subject-changes-to-google-apis-terms-of.html)

*•Asking developers to make reasonable efforts to keep their private keys private and not embed them in open source projects.*

https://github.com/squid808/gShell/blob/master/gShell/gShell/dotNet/Utilities/OAuth2/OAuth2Group.cs

**Comment by squid808** [comment]
Thanks Linda, I am aware of this and have every intention of getting this resolved. I'm currently working on some significant scope issues that are preventing me from putting out my next release, in which I will be requiring users to generate their own project info, via methods I introduced in the most recent release. As soon as I can get that sorted out, I can move forward.

**Comment by LindaLawton** [comment]
Just reset it on Google Developers console now then.   If you leave it in here and someone spams it your whole Google developers account will be banned by Google and not just this one project.    BTW I am Daimto on stack.   I like your project still playing with that issue you posted on stack.

**Comment by squid808** [comment]
The secret has been reset. Thank you Linda for bringing this to my attention. I will properly address the issue in the next future release!
