### ISSUE TITLE
invoke-scopemanager error

### ISSUE THREAD

**Issue by jparodi** [squid808/gShell#9]
Suddenly today (last used this earlier in the week), I became unable to run gShell commands. Any command run returned back a notification that the there is no current scope for that command. 

When running invoke-scopemanager it errors out after I choose the requisite scopes.  
>Invoke-ScopeManager : One or more errors occurred.
At line:1 char:1
+ Invoke-ScopeManager -Domain DOMAIN.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-ScopeManager], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,gShell.Cmdlets.Utilities.ScopeHandler.InvokeScopeManager

Troubleshooting steps taken:
* remove gShell_OAuth2.bin file
* remove authorization via https://security.google.com/settings/security/permissions?pli=1
* test simple GET requests in https://developers.google.com/admin-sdk/directory/v1/reference/users/get#try-it (**successful**)
* try with a newly generated domain admin account (**presented same error**)
* uninstall and reinstall gShell (was already running latest version)

**Comment by squid808** [comment]
Hi jparodi,

Please see this post in the discussion groups:
https://groups.google.com/forum/#!topic/gshell-discuss/BSWZM9PVvwQ

Unfortunately I am away on travels and have yet to update the wiki, but you
will need to go to the Google Developer's Console and create a project. It
only takes a few minutes to do. Once I'm back I'll update the wiki if
nobody else can get to it first.

Please let me know if that helps.

Regards,

Spencer

**Comment by jparodi** [comment]
Hello Spencer, 
Thank you for the quick response.  This makes total sense and I appreciate your rapid response!
Take care and have safe travels
Best,
Jon
